YOLOV3:
  CFG: "./detector/YOLOv3/cfg/yolov3-custom.cfg"
  WEIGHT: "./detector/YOLOv3/weight/obj_detection.weights"
  CLASS_NAMES: "./detector/YOLOv3/cfg/classes.names"
  #CFG: "C:/Users/venny/Desktop/Project/yolov3.cfg"
  #WEIGHT: "C:/Users/venny/Desktop/Project/yolov3.weights"
  #CLASS_NAMES: "C:/Users/venny/Desktop/Project/coco.names"

  SCORE_THRESH: 0.7
  NMS_THRESH: 0.3
